apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commerce-app
  template:
    metadata:
      labels:
        app: commerce-app
    spec:
      containers:
      - name: commerce-app
        image: adexxy/commerce-app:0.1.0-18
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: commerce-app-service
spec:
  type: NodePort
  selector:
    app: commerce-app
  ports:
  - port: 83
    targetPort: 3000